apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <html>
    <head><title>Simple NGINX</title></head>
    <body>
      <h1>Ini tampilan dari NGINX dan nama saya Ponang</h1>
    </body>
    </html>
