apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-config
data:
  index.html: |
    <html>
    <body>
      <h1>Ini tampilan dari HTTPD dan nama saya Ponang. Tambah text</h1>
    </body>
    </html>
