apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-httpd
  template:
    metadata:
      labels:
        app: simple-httpd
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          volumeMounts:
            - name: httpd-html
              mountPath: /usr/local/apache2/htdocs/index.html
              subPath: index.html
      volumes:
        - name: httpd-html
          configMap:
            name: httpd-config
            items:
              - key: index.html
                path: index.html
